package eu.wauz.wauzraycaster;

import eu.wauz.wauzraycaster.game.GameWindow;
import eu.wauz.wauzraycaster.game.isaac.IsaacMap;
import eu.wauz.wauzraycaster.game.terraria.TerrariaMap;
import eu.wauz.wauzraycaster.textures.GameTexture;
import eu.wauz.wauzraycaster.textures.GameTileset;

/**
 * A demo application to show the capabilities of the engine.
 * Renders a randomly generated navigatable world for a Terraria clone.
 * 
 * @author Wauzmons
 * 
 * @see TerrariaCellularAutomataDemo Map Generator Demo
 * @see TerrariaMap
 */
public class IsaacDemo {

	/**
	 * A map is generated by a cellular automaton, filling an array with integers.
	 * A tileset is created by loading textures from the resources.
	 * The integers correspond to the textures, in the order they have been added.
	 * The Terraria Map creates 16x16 sized blocks from the assigned textures.
	 * A 720x480 pixel window with 60 fps is created, to load the map.
	 * A controllable 2D camera is added to the map, before the game starts.
	 * 
	 * @param args
	 * 
	 * @see GameWindow
	 */
	public static void main(String[] args) {
		int[][] mapMatrix = new int[13][9];
		GameTileset tileset = new GameTileset();
		tileset.add(new GameTexture("images/isaac/floor.png", 32));
		tileset.add(new GameTexture("images/isaac/wall.png", 32));
		tileset.add(new GameTexture("images/isaac/corner.png", 32));
		tileset.add(new GameTexture("images/isaac/door_closed.png", 32));
		tileset.add(new GameTexture("images/isaac/door_opened.png", 32));
		IsaacMap map = new IsaacMap(mapMatrix, tileset);
		map.setBlockSize(32);
		GameWindow game = new GameWindow(416, 288);
		game.setFps(1);
		game.loadMap(map);
		game.setTitle("The Binding of Joe");
		game.start();
	}
	
}
