package eu.wauz.wauzraycaster;

import java.awt.Color;

import eu.wauz.wauzraycaster.entity.terraria.TerrariaCamera;
import eu.wauz.wauzraycaster.game.GameWindow;
import eu.wauz.wauzraycaster.game.terraria.TerrariaMap;
import eu.wauz.wauzraycaster.textures.GameTexture;
import eu.wauz.wauzraycaster.textures.GameTileset;

/**
 * A demo application to show the capabilities of the engine.
 * Renders a randomly generated navigatable world for a Terraria clone.
 * 
 * @author Wauzmons
 * 
 * @see TerrariaCellularAutomataDemo Map Generator Demo
 * @see TerrariaMap
 */
public class TerrariaDemo {

	/**
	 * A map is generated by a cellular automaton, filling an array with integers.
	 * A tileset is created by loading textures from the resources.
	 * The integers correspond to the textures, in the order they have been added.
	 * The Terraria Map creates 16x16 sized blocks from the assigned textures.
	 * A 720x480 pixel window with 60 fps is created, to load the map.
	 * A controllable 2D camera is added to the map, before the game starts.
	 * 
	 * @param args
	 * 
	 * @see GameWindow
	 */
	public static void main(String[] args) {
		int[][] mapMatrix = new int[1200][350];
		GameTileset tileset = new GameTileset();
		tileset.add(new GameTexture("images/terraria/dirt.png", 16));
		tileset.add(new GameTexture(Color.BLUE.darker().darker(), 16));
		tileset.add(new GameTexture("images/terraria/stone.png", 16));
		tileset.add(new GameTexture("images/terraria/leaf.png", 16));
		tileset.add(new GameTexture("images/terraria/water.png", 16));
		TerrariaMap map = new TerrariaMap(mapMatrix, tileset);
		map.setBlockSize(16);
		map.generate();
		GameWindow game = new GameWindow(720, 480, 1);
		game.setFps(60);
		game.loadMap(map);
		game.placeCamera(new TerrariaCamera(400, 120, 0, 0, 0, 0));
		game.setTitle("Terrario");
		game.start();
	}
	
}
